name: Security Scorecards

on:
  schedule:
    - cron: '17 3 * * 1'
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  scorecards:
    name: OSSF Scorecards
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run OpenSSF Scorecards
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@5c8a8a642e79153f5d047b10ec1cba1d1cc65699 # v3
        with:
          sarif_file: results.sarif
